### ISSUE TITLE
Task 2: Registro del usuario (Frontend)

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#114]
Se espera que al terminar esta tarea el Frontend de la app para el registro de nuestros usuarios sea funcional con el backend desarrollado en la issue #112

**Comment by javgrogom** [comment]
@FranCamposC @fracamcam sabes en que carpeta está el archivo del formulario de registro de usuario? Lo estoy buscando en la rama #114 y no lo encuentro.

**Comment by FranCamposC** [comment]
Hola Javi,  aún lo tengo hecho en local, en cuanto lo tenga refinado lo subo. Perdona el retraso.

**Comment by javgrogom** [comment]
> Hola Javi, aún lo tengo hecho en local, en cuanto lo tenga refinado lo subo. Perdona el retraso.

Nah no te preocupes, luego reviso y añado las restricciones al formulario

**Comment by FranCamposC** [comment]
Buenos días Javier, he subido el frontend a la rama. Añade las restricciones pertinentes a los distintos campos.@javgrogom

**Comment by javgrogom** [comment]
> Buenos días Javier, he subido el frontend a la rama. Añade las restricciones pertinentes a los distintos campos.[@javgrogom](https://github.com/javgrogom)

Perfe @FranCamposC , hoy mismo las añado cuanto antes

**Comment by javgrogom** [comment]
@FranCamposC  Ya he añadido las restricciones, el formulario funciona perfecto:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/1c1e39bf-c62a-48f5-94c0-d56fbd4da08e)



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/97d7390e-14d9-4024-9451-07df6e8c5388)


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/aac471f6-fbcd-45e5-8953-1b24a6b3d83d)

Las restricciones son:
Para nombre de usuario y nombre, un minimo de 3 caracteres y un maximo de 30
Para apellidos, un minimo de 3 y un maximo de 60
En contraseña, un minimo de 8 caracteres y debe incluir una minuscula, una mayuscula, un número y un caracter especial
En correo, debe ser un formato valido de correo
Y en fecha de nacimiento, no te permite escoger fechas futuras ni tampoco fechas de hace mas de 200 años.

Con esto consideraría terminado la vista del registro de usuario, hago commit en cuando pueda y lo subo.

**Comment by javgrogom** [comment]
A la espera de que la revisen
