### ISSUE TITLE
Task 16: Listado de Servicios filtrado [Ciudad/Profesión] (Frontend)

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#128]
Crear una vista que utilice la estructura realizada en la issue #127 para crear una buscador que filtre los datos por los criterios establecidos

**Comment by alisanhos** [comment]
El listado de servicios ya funciona. Podemos filtrarlo según el lugar o la profesión (este es con un desplegable).

Se ha hecho de una forma mas dinámica. Accedes al botón de buscar servicios y ahí te lleva a una pagina con todos los servicios. En esa pagina hay unos parametros que podemos rellenar:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/53cdb52b-b5f3-4187-a901-16ed096383d8)

Mediante se van rellenando los campos, se va filtrando al mismo tiempo. Eso si, como esta puesto que sea OnChange, esto causa que haga demasiadas peticiones y se bloquee:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/960e52ad-bcbe-43b9-8c37-e1c76a1a2efd)

Para solucionarlo podemos usar eso: [](https://stackoverflow.com/questions/53071774/reactjs-delay-onchange-while-typing) 

Ademas de eso, quedaría hacer que los card se vean de mejor forma ya que hace que mucho espacio quede inutilizado. 

También borrar los botones en home y añadir el buscar servicios al navbar.

**Comment by alisanhos** [comment]
Ya se ha solucionado el tema de OnChange. Se le ha puesto un delay de 1000 ms una vez se deja de escribir:

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/cce79feb-f5c1-4802-a555-ffc502e28142)

Ademas de ello se ha mejorado la vista del listado y se ha hecho que sea responsive. Solo queda enlazarlo con la imagen de perfil del usuario. Por ahora he puesto una imagen base en todas.



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/ad0f3303-25b5-403b-bd07-568b6e83ed72)
