### ISSUE TITLE
Task 18 - Listado de Servicios por Usuario (Frontend)

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#130]
Usando la funcionalidad creada en la issue #129, crear una vista que muestre la lista de servicios del usuario autenticado

**Comment by alisanhos** [comment]
Esta todo hecho, lo único que pasa es que nos da problemas el obtener el usuario que esta logueado.

**Comment by alisanhos** [comment]
Ya se muestran los servicios del usuario


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/304474a9-224c-4f2a-aade-4e02330a6df2)

**Comment by alisanhos** [comment]
@adrgarcha @pabmatang en el listado de servicios de usuario, hay que meter el enlace en cada card que lleve al detalle de servicio. 

Está en /frontend/src/components/service/servicesUserCard.jsx

Debéis añadir la dirección de detalle de servicio en la linea 21:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/65f9bb68-4ce5-46ef-814f-2b2f62fb241e)
