### ISSUE TITLE
Task 24 - Listado de Contratos de Usuario (Frontend)

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#136]
Creación de vista que complemente la funcionalidad desarrollada en la issue #135

**Comment by alvhidrod** [comment]
Para poder ejecutar las funciones crud de contrato se deberán usar las siguientes urls(en todas se omite el localhost:8080 por comodidad del escritor:
Create:
/contracts/create/Id_del_servicio_asociado/
Edit de contrato:
/contracts/edit/Id_del_contrato_a_editar/
Edit de state:
/contracts/edit/Id_del_contrato_a_editar/id_del_nuevo_state/
Delete:
/contracts/delete/Id_del_contrato_a_eliminar/
Listado de contratos del cliente que ha iniciado sesión:
contracts/clientList/
Listado de contratos del trabajador que ha iniciado sesión:
contracts/workerList/

Nota: En las dos últimas funciones solamente se devuelven los contratos en los que el usuario logueado es el cliente o el trabajador respectivamente, por ejemplo si "Sam" inicia sesion y ejecuta la funcion worker list solamente saldrán los contratos donde él sea el worker, para saber en los que es el cliente se necesita usar la url clientList
@pabcueper @alisanhos

**Comment by pabcueper** [comment]
FALTA POR HACER:
 
- Contract Card de Client y Worker
- Mostrar nombres de client y worker respectivamente.
- Dividir por columnas client y worker en el listado de contratos

**Comment by alisanhos** [comment]
Se ha terminado el Card, tanto de cliente como Worker. Ya se muestra el nombre de los usuarios.

En vez de dividirlo en columnas, lo he hecho por filas:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/7dcae039-8e4a-4d59-a338-7b1068236139)

**Comment by alisanhos** [comment]
@Samalbalat @alvhidrod.

He estado hablando con Adrián y debemos usar **Authori_z_ation** y no **Authori_t_ation**. He modificado dos lineas del backend y todo funciona sin problemas, sin tener que hacer uso del CORS_ALLOWED_HEADERS.
Adrian ya lo había preparado para eso, y como estabais usando Authoritation no funcionaba porque escon z.



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/95e5d91c-569b-4c2f-a006-0b464e2d82a0)



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/0b254a90-63ff-48c3-8d0a-8e67bc21594e)
