### ISSUE TITLE
Task 27 - Arreglar Creación de Contrato (Backend)

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#137]
Encontrar y solventar el error que impide la correcta creación de contratos, y en su defecto notificar al equipo de frontend, la posible causa fuera del backend

**Comment by JoseLuisCobo17** [comment]
Listado de restricciones de contratos:
1. 4 primeros parámetros no se deben de meter en la creación (solo  se puede modificar coste, fecha inicio, fecha final y descripción)
2. Descripción 500 caracteres
3.  No pueden tener coste negativo y mayor que 0 
4. Fecha inicial mínima en el momento 
5.  Fecha final posterior a la del inicio

**Comment by javgrogom** [comment]
El error a arreglar, a parte de lo dicho anteriormente por Jose Luis, es este:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/e776f959-1b8d-4f1c-8d42-70dbf516d2bb)

Desde front voy a mirar que solución tiene

**Comment by javgrogom** [comment]
El error del map está arreglado. Aun así, mirad aqui un poco los requisitos a cumplir:
https://github.com/ciaolavoro/ciao-lavoro/issues/138

E investigad como hacer la parte de backend
