### ISSUE TITLE
Task 28 - Arreglar Creación de Contrato (Frontend)

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#138]
Encontrar y solventar, el error que impide la creación del contrato, en su defecto notificar al equipo de backend de su inexistencia en el frontend

**Comment by javgrogom** [comment]
El error es este:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/882e57e8-93bf-4d2f-a2e9-1d42486af84c)

Hay que buscarle la solución ya sea back o front

**Comment by javgrogom** [comment]
Arreglado el asunto del map.
De todas formas:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/8bdb6397-11bd-450f-8355-2f295dc53679)

Ademas, salen campos que no deberian de ser modificados por el usuario:
Listado de restricciones de contratos:

4 primeros parámetros no se deben de meter en la creación (solo se puede modificar coste, fecha inicio, fecha final y descripción)
Descripción 500 caracteres
No pueden tener coste negativo y mayor que 0
Fecha inicial mínima en el momento
Fecha final posterior a la del inicio

Por ultimo, la creación de contrato sale en el menú inicial:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/b348ef62-247a-4ac9-a34b-26bf21fcf793)


Cuando debería de salir como un botón en los servicios en el listado de servicio.

**Comment by javgrogom** [comment]
Esta tarea tiene dependencia de esta issue:
https://github.com/ciaolavoro/ciao-lavoro/issues/132

Se necesita tener la vista de los servicios disponibles para poner el botón y poder asociar trabajador, usuario y trabajo al contrato.
