### ISSUE TITLE
Doc - Contribución a la base de datos S2

### ISSUE THREAD

**Issue by javgrogom** [ciaolavoro/ciao-lavoro#158]
Esta tarea consiste en lo siguiente:
-Recopilar el feedback de las clases y pasarlo a limpio
-Añadir dicho feedback tanto a nuestra base de conocimientos propia (la wiki) como al docusaurio de la base de conocimientos grupal.
-Redactar el informe de la contribucion a la base de datos

El documento de contribución a la base de datos
Debe llamarse 6-report.md

El enlace a la Base de Conocimientos compartida.
El contenido específico que ha aportado el equipo, que debe incluir, al menos, el feedback específico recibido y las anotaciones sobre el feedback general.
Las acciones de consolidación que se han llevado a cabo. Si no se ha realizado ninguna, especifique "No se han realizado acciones de consolidación".

Se realizará en la rama docs

Enlaces de interés:
Base de conocimientos grupal:
https://github.com/ISPP-2324/BGC
https://bgcc.vercel.app/

Base de conocimientos individual:
https://github.com/ciaolavoro/ciao-lavoro/wiki

El feedback también se puede localizar en la carpeta "docs" del proyecto

**Comment by javgrogom** [comment]
Actualizada la base de datos individual y grupal con nuevo contenido gracias al feedback individual y grupal de la semana 5

**Comment by javgrogom** [comment]
Se me olvico moverla a In Progress. De todas formas esta tarea estará en continuo "In Progress" hasta que estemos cerca del final del Sprint porque trata de documentación que se actualizará todas las semanas en base al feedback.

**Comment by javgrogom** [comment]
Contribuido a la base de conocimientos individual y común de la semana 6.
En la común a parte de poner las anotaciones del grupo 6 se han añadido anotaciones de interés común para todos los grupos

**Comment by javgrogom** [comment]
Contribuido a la base de datos de conocimientos individual y grupal de la semana 7

**Comment by Samalbalat** [comment]
@javgrogom he revisado el documento lo que si he de decir es que hay apartados del Uso de la IA vacíos, se debe a algo?
