### ISSUE TITLE
Fix 1: Eliminar dependencia de react-icons-kit

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#166]
Actualmente, hay una dependencia que es necesaria instalar para iniciar el Frontend. Sin embargo, existe una carpeta dentro del proyecto para copiar los iconos que se deseen y agregarlos como componente para usarlos en cualquier lugar de la aplicación. Se busca eliminar la dependencia para optimizar el rendimiento de la página, y usar la forma descrita para utilizar iconos.

**Comment by javgrogom** [comment]
@adrgarcha ya he corregido y eliminado la dependencia, haciendo que ahora use iconos de la carpeta.

De paso se ha reformulado la forma en la que funcionaba el toggle para ver o no la contraseña.
