### ISSUE TITLE
Task 39 - Storyboard

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#175]
Consiste en hacer un guion y representar la historia en forma de viñetas para vender en forma de anuncio la aplicación a los usuarios.

Ejemplo de StoryBoard:

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/94b5e7c6-88a7-46aa-95ac-5d0d19fb0ebc)

**Comment by javgrogom** [comment]
StoryBoard:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/a068b026-3d7a-4e95-b3dc-2adfd11c9634)
Escena 1: 3 amigos quedan y uno tiene unos pelos de locos, ¡Hay que arreglar eso!

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/cbec7201-f347-409b-868e-d44ed86d6aa1)
Escena 2:  Pero estan tristes porque la peluquería tiene mucha clientela y no pueden ir

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/d329a60a-c533-4805-9019-b32474751f21)
Escena 3: Entonces a uno se le ocurre una solucion

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/5b39fd08-8389-4198-8345-f24a6d180f12)
Escena 4: Acceden a CiaoLavoro y buscan a alguien que sea peluquero

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/3b87fb1b-423e-4a50-aa60-e1954d6dc06d)
Escena 5: Llega el peluquero

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/be99e26a-0f65-4496-b69c-391d13be1235)
Escena 6

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/8771cd23-6767-4bab-86ac-d375f32e204c)
Escena 7:  Le corta el pelo

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/5da352e0-438a-4d3d-b248-e2a3cb9c7d4c)
Escena 8: ¡Todos felices! ¡Gracias a CiaoLavoro nuestros tres amigos han resuelto su problema de forma rapida y efectiva!
