### ISSUE TITLE
Fix Task 23 - Listado de Contratos por Usuario

### ISSUE THREAD

**Issue by pabcueper** [ciaolavoro/ciao-lavoro#191]
Debe cambiarse el backend que lista los contratos por usuario para que, en lugar de enviar los servicios del usuario logueado, muestre los servicios de un usuario concreto pasado a través de la ID.

Esta tarea debe resolverse para continuar con el desarrollo de la Task 24.

@alvhidrod @Samalbalat

**Comment by Samalbalat** [comment]
Se cierra con la PR de la rama: Task-2.24---Listado-de-contratos-de-usuario-frontend/136
