### ISSUE TITLE
Fix 5 - Creacion Contratos a uno mismo

### ISSUE THREAD

**Issue by javgrogom** [ciaolavoro/ciao-lavoro#201]
Los contratos actualmente no tienen ningún limitador que impida a los usuarios que tienen creados servicios contratar sus propios servicios. Además, por redundancia esto da un error cuando se intenta.

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/12e9285a-750d-47fb-a57a-eeffed5900b0)

**Comment by javgrogom** [comment]
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/591a813c-d527-4230-a77e-f7f014e10f9c)

Es necesario por parte de backend hacer una función que dado un serviceId y un usuario, manda de respuesta si están asociados o no.

Si estan asociados responde un "true" o algo por el estilo, si no, un "false" o algo por el estilo. 
La idea es usar esta función para verificar si el servicio a contratar pertenece al usuario registrado, para que no se pueda crear contratos a uno mismo.

**Comment by alvhidrod** [comment]
@javgrogom Creada la función, esta devuelve un json con la variable user_state la cual su valor es True si el usuario no coincide con el del servicio y su valor será False si estos dos coinciden.
La url a seguir es 'http://127.0.0.1:8000/service/<int:service_id>/userProperty/' Siendo service id el id del servicio que queremos comparar y el user id con el que se compara es el del usuario logueado. Si se requiere de algún cambio en la función que se me avise y sin problemas lo cambio en un momento.
