### ISSUE TITLE
Fix 10 - Mejora inicio sesión (Frontend)

### ISSUE THREAD

**Issue by FranCamposC** [ciaolavoro/ciao-lavoro#219]
- Si no existe el useer, da error 404, hay que poner un validate de "Usuario no existe"
- Poner el ojito para uqe se vea la contraseña

**Comment by javgrogom** [comment]
El problema "Si no existe el user, da error 404, hay que poner un validate de "Usuario no existe"" es de backend. Se requeriría a alguien de backend que en la hora de hacer el login compruebe en la base de datos que el usuario no existe y mande el mensaje de error.

**Comment by javgrogom** [comment]
Despues de hablar con backend el 404 es algo que es normal que salga, no es un error. Eso si, hay que hacer que la aplicación muestre un cartel.
