### ISSUE TITLE
Fix 17 - Arreglar creación de servicio (Frontend)

### ISSUE THREAD

**Issue by FranCamposC** [ciaolavoro/ciao-lavoro#226]
- Da fallos el boton de crear (se piensa que es del token)
- Validaciones y restricciones
- Estructura del form
- Cuando un usuario crea un servicio de una profesion que ya tiene, debe restringirse
- Al crear un servicio no debería de pedir el email, ya que lo debería coger directamente del user.

**Comment by adrgarcha** [comment]
Ya se ha arreglado la creacion de servicio en el Fix 2.18. Se procede a cerrar la Issue, ya que no tiene relevancia.
