### ISSUE TITLE
Hotfix 2 - Arreglo errores relacionados con Usuario

### ISSUE THREAD

**Issue by diegonqui** [ciaolavoro/ciao-lavoro#230]
- No puede haber varios gets en una misma entidad, cambiarlo ya.
- Meterle constraints a los updates ya que no tiene ninguno, también en el post.
- Listar usuarios no debería existir.
- Permisos en el views.py se tienen que reasignar.
- Quitar las lineas repetidas en el models.py
- UserServiceList debería usar el token.
- En detalle de usuario no debe utilizar id, también el token.
- En vez de eliminar usuario, deshabilitar y que no salga.
- Lenguaje como choice o una lista que se vaya actualizando como string.
- Ciudad como choice.
- Fechas en formato ESP?
- La falta de relleno en alguno de los campos resulta en errores 500 o mensajes poco claros. (Hacer defaults para los campos)
- Revisar views (validaciones, formulario de edit, revisar que se necesita y que no)
- Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente)
- Revisar URLs
- ADICIONALMENTE, usar la API de verificación de Email del registro de Usuario

Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by JoseLuisCobo17** [comment]
No puede haber varios gets en una misma entidad, cambiarlo ya. **JL**
Meterle constraints a los updates ya que no tiene ninguno, también en el post. **HECHO(REVISAR JL)**
Listar usuarios no debería existir. **JL**
Permisos en el views.py se tienen que reasignar. **JL**
Quitar las lineas repetidas en el models.py **JL**

En detalle de usuario no debe utilizar id, también el token. **JL**
En vez de eliminar usuario, deshabilitar y que no salga. **JOAQUIN**
Lenguaje como choice o una lista que se vaya actualizando como string. **SIN PRIORIDAD**
Ciudad como choice. **SIN PRIORIDAD**

La falta de relleno en alguno de los campos resulta en errores 500 o mensajes poco claros. (Hacer defaults para los campos) **FRONTEND**
Revisar views (validaciones, formulario de edit, revisar que se necesita y que no)  **JOAQUIN**
Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente)  **JOAQUIN**
Revisar URLs  **JOAQUIN**
ADICIONALMENTE, usar la API de verificación de Email del registro de Usuario  **JOAQUIN**
Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by JoseLuisCobo17** [comment]
Permisos en el views.py se tienen que reasignar. JL
Quitar las lineas repetidas en el models.py JL


En vez de eliminar usuario, deshabilitar y que no salga. JOAQUIN
Lenguaje como choice o una lista que se vaya actualizando como string. SIN PRIORIDAD
Ciudad como choice. SIN PRIORIDAD


Revisar views (validaciones, formulario de edit, revisar que se necesita y que no) JOAQUIN
Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente) JOAQUIN
Revisar URLs JOAQUIN
ADICIONALMENTE, usar la API de verificación de Email del registro de Usuario JOAQUIN
Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by JoseLuisCobo17** [comment]
En vez de eliminar usuario, deshabilitar y que no salga. JOAQUIN
Lenguaje como choice o una lista que se vaya actualizando como string. SIN PRIORIDAD
Ciudad como choice. SIN PRIORIDAD

Revisar views (validaciones, formulario de edit, revisar que se necesita y que no) JOAQUIN
Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente) JOAQUIN
Revisar URLs JOAQUIN
ADICIONALMENTE, usar la API de verificación de Email del registro de Usuario JOAQUIN
Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by JoseLuisCobo17** [comment]
En vez de eliminar usuario, deshabilitar y que no salga. JOAQUIN

Revisar views (validaciones, formulario de edit, revisar que se necesita y que no) JOAQUIN
Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente) JOAQUIN
Revisar URLs JOAQUIN

Lenguaje como choice o una lista que se vaya actualizando como string. SIN PRIORIDAD
Ciudad como choice. SIN PRIORIDAD

Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by Joaquin-Arregui** [comment]
Revisar views (validaciones, formulario de edit, revisar que se necesita y que no) JOAQUIN
Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente) JOAQUIN
Revisar URLs JOAQUIN

Lenguaje como choice o una lista que se vaya actualizando como string. SIN PRIORIDAD
Ciudad como choice. SIN PRIORIDAD

Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)
