### ISSUE TITLE
Hotfix 3 - Arreglo errores relacionados con Servicio

### ISSUE THREAD

**Issue by diegonqui** [ciaolavoro/ciao-lavoro#231]
- ValidationError no valida en frontend
- PermissionDenied solo cuando no tienes permiso, para el resto de situaciones(propiedad que no cumple las constraints)ValidationError
- La falta de relleno en alguno de los campos resulta en errores 500 o mensajes poco claros. (Hacer defaults para los campos)
- Fechas en formato ESP?
- Profesión como campo de texto?
- Quitar la foto hardcodeada y meter un código funcional para mostrar las imágenes
- UserServiceViewSet se puede eliminar
- Aumentar lista de profesiones
- No hay error al mal introducir el correo electrónico en servicio
- JobEdit y Creation no tiene validaciones 
- Revisar views (validaciones, formulario de edit, revisar que se necesita y que no)
- Revisar serializers (borrar y lo que se usa mover de API a su sitio correspondiente)
- Revisar URLs

Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by Joaquin-Arregui** [comment]
UserServiceList debería obtener el usuario por el token
