### ISSUE TITLE
Hotfix 4 - Arreglo errores relacionados con Contrato

### ISSUE THREAD

**Issue by diegonqui** [ciaolavoro/ciao-lavoro#232]
- ValidationError no valida en frontend
- PermissionDenied solo cuando no tienes permiso, para el resto de situaciones(propiedad que no cumple las constraints)ValidationError
- - La falta de relleno en alguno de los campos resulta en errores 500 o mensajes poco claros. (Hacer defaults para los campos)
- ¿Fechas en formato ESP?
- Profesión como campo de texto??
- Serializer de contrato debería estar dentro de la carpeta contracts
- Añadir en las funciones que accept worker y client se vuelvan true cuando lo acepte cada uno (añadir botón)
- Cambiar workerList para que filtre por service.user en vez de worker
- Revisar permisos: list, delete, edit…
- Request.user arreglarlos(no debe salir) -> token
- Cuando se crea contrato aparece aceptado -> debe estar en proceso
- Precios negativos en el contrato
- La creación de contratos no persistía
- El formulario de contrato no es consistente en la fechas (final antes que inicio y similares restricciones estaban ausentes)
- Servicios repetidos en los formularios de contrato
- Mismo user como cliente y trabajador en los contratos
- Revisar las URLs
- Revisar las Views (formularios, revisar que se necesita y que no)
- Revisar los Serializers (borrar y lo que se usa mover de API a su sitio correspondiente)

Por lo que sea, mirar el [Acta Reunión Marzo 19 - 2024](https://docs.google.com/document/d/178CSFebxnA0Xb46L-1O0ps72yUJg03lpy5r1Q4Axzik/edit?usp=sharing)

**Comment by Samalbalat** [comment]
Aquí dejo los tests del ThunderClient

[thunder-collection_Tests de Contrato.json](https://github.com/ciaolavoro/ciao-lavoro/files/14668850/thunder-collection_Tests.de.Contrato.json)

Porfavor leed el commit previo para entender lo que se ha hecho y recordad que los datos estáticos en las urls dependen de vuestra DB
