### ISSUE TITLE
Doc - Usuarios Piloto: CA y PE S2

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#291]
**Descripción general**
Teniendo en cuenta los conocimientos dados por el profesorado (en ev.us.es) realizar un commitment agreement para los usuarios piloto al igual que un performance evaluation de los mismos. Se crearán dos archivos dentro de la carpeta Docs: pilotUsersCommitmentAgreement.md, que será la plantilla del commitment agreement de Usuarios Piloto; y PilotUsersPerformanceEvaluation.md, además de una carpeta PilotUsersCA donde se guardarán los CA de los Usuarios Piloto.

**Comment by FranCamposC** [comment]
Creada por equivocación, estos archivos ya han sido creados
