### ISSUE TITLE
Doc - Información de los Usuarios Piloto S2

### ISSUE THREAD

**Issue by Samalbalat** [ciaolavoro/ciao-lavoro#292]
**Descripción general**
Tomando como referencia lo expresado por los profesores en el documento MinimumInformationFromPilotUsers_Gathered-ByForm crear un documento InformationProvidedByPilotUsers.md en consecuencia (Revisar ev.us.es)

**Comment by javgrogom** [comment]
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/e1912e6c-950a-44fd-afd6-4515f0fe0243)

**Comment by javgrogom** [comment]
Terminado. Pendiente de revisión

**Comment by javgrogom** [comment]
@diegonqui Ya esta terminado el documento y pendiente de revisión
