### ISSUE TITLE
Doc - Storyboard de segundo caso de uso

### ISSUE THREAD

**Issue by javgrogom** [ciaolavoro/ciao-lavoro#297]
**Descripción general**
Realizar un segundo storyboard para las presentaciones con el segundo caso de uso (Persona que busca empleo)

**Comment by javgrogom** [comment]
Realizado el segundo Storyboard. Se va a subir en nada

**Comment by Samalbalat** [comment]
La storyboard está super chula! Es una buena iteración de la primera ahora oon nuevos actores!, Soy muy fan!
