### ISSUE TITLE
Doc - Reporte de Contribución a la Base de Conocimiento

### ISSUE THREAD

**Issue by diegonqui** [ciaolavoro/ciao-lavoro#303]
**Descripción General:**
Crear un Reporte de Contribución a la Base de Conocimiento, generando el archivo report.md. Añadirlo a la carpeta Docs dentro del proyecto en Github.

**Comment by javgrogom** [comment]
Realizado en esta issue:

https://github.com/ciaolavoro/ciao-lavoro/issues/332

**Comment by javgrogom** [comment]
Realizado en esta issue:

https://github.com/ciaolavoro/ciao-lavoro/issues/332
