### ISSUE TITLE
Doc - Crear Vídeo Demo S2

### ISSUE THREAD

**Issue by diegonqui** [ciaolavoro/ciao-lavoro#305]
Crear vídeo de la demo de la aplicación. @Joaquin-Arregui se encarga de grabarlo y @JoseLuisCobo17 de revisarlo y dar el feedback necesario. Se permite feedback adicional por parte de otros miembros del equipo.

**Comment by alisanhos** [comment]
He revisado el video y se ve perfectamente, ademas que hace zoom en las partes importantes.
