### ISSUE TITLE
Task 2 - Gamificación (Backend)

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#323]
**Descripción general**
Implementar la gamificación en la parte del Backend, cuando gastes X € consigues X puntos.
¡¡¡¡¡¡ACTUALIZAR TESTS¡¡¡¡¡¡

**Comment by javgrogom** [comment]
Desde frontend pienso que podría ser interesante tb una función que devuelva el número de puntos que tienes

**Comment by Joaquin-Arregui** [comment]
De acuerdo, lo haré
