### ISSUE TITLE
Task 3 - Gamificación (Frontend)

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#324]
**Descripción general**
Implementar la gamificación en el Frontend, cuando se gasten X € se podrán obtener X puntos.

**Comment by javgrogom** [comment]
Si no lo he entendido mal, la implementación de esta tarea es el descuento de los puntos a la hora de pagar no?

**Comment by javgrogom** [comment]
Necesito ayuda de backend para que se implemente el estado de "Pagado y canjeado puntos" a los contratos.

**Comment by javgrogom** [comment]
Implementada la vista de puntos.
