### ISSUE TITLE
Task 4 - Ajustar la promoción de Servicios (Backend)

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#325]
**Descripción general**
Actualmente las promociones no tienen tiempo de expiración. Implementar tiempos de expiración y ligarlo con el tema de la gamificación.
¡¡¡¡¡¡ACTUALIZAR TESTS¡¡¡¡¡¡

**Comment by Samalbalat** [comment]
@alvhidrod se han realizado los tests de sendas funcionalidades, al ser un listado el segundo método no tiene negativo, respecto a la gamificación se encarga @Joaquin-Arregui, por lo que se me ha dicho con lo realizado basta te recomiendo ver el commit (https://github.com/ciaolavoro/ciao-lavoro/commit/5bb0bd27fbebdced73ec653884133850049aedfc) 5bb0bd27fbebdced73ec653884133850049aedfc
