### ISSUE TITLE
Doc - Gestion de la Configuracion

### ISSUE THREAD

**Issue by javgrogom** [ciaolavoro/ciao-lavoro#344]
**Descripción general**
Editar el documento de gestion de la configuración para redactar la política de comunicación a la hora de haber problemas en las tareas o de proponer tareas nuevas

**Comment by javgrogom** [comment]
Tambien hay que añadir que las issues sin personas asignadas es porque son grupales

**Comment by adrgarcha** [comment]
✔ Documento correctamente redactado y con la información requerida.
