### ISSUE TITLE
Fix 2 - Edición de perfil

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#354]
**Descripción general**
Los usuarios piloto han encontrado varios problemas con la edición del perfil de usuario:

- Se cierra sesión al modificar datos de usuario (comportamiento esperado, a revisar).
- Permite subir archivos que no son imágenes.
- Se propone hacer el campo de Idioma como un selector.
- He introducido la fecha 28/02/2031 y al pulsar en guardar cambios, ha saltado un error.

**INDICAR EN LA PR SI NO SE HA LLEGADO A IMPLEMENTAR CUALQUIERA DE LAS PROPUESTAS ANTERIORES**

**Comment by FranCamposC** [comment]
Recomiendo también poner un desplegable en el campo Idioma. Lo he hecho en el registro por si lo quereis usar.
