### ISSUE TITLE
Fix 3 - Servicios

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#355]
**Descripción general**
Los usuarios piloto han encontrado los siguientes problemas en los servicios:

- En el apartado Ciudad de la creación de un servicio no permite meter espacios ni tampoco la ñ, por lo que localizaciones como "Castilla la mancha" o "Logroño" no se pueden meter.✅
- Se propone hacer que las ciudades sean un selector. 💢
- Al buscar servicios, si se le da a la tecla Intro se reinicia el buscador.✅
- Se imprimen más cosas de la cuenta por consola. ✅
- Se propone la búsqueda por usuario.✅
- Se puede quitar el check de activo sin primero darle a editar, entonces no se guarda el cambio. ✅

**INDICAR EN LA PR SI NO SE HA LLEGADO A IMPLEMENTAR CUALQUIERA DE LAS PROPUESTAS ANTERIORES**

**Comment by alisanhos** [comment]
De aquí actualmente esta todo hecho, el único problema es que el desplegable de ciudades tarda demasiado. Adrián ha propuesto usar una API en vez de el archivo. El problema es que no consigo hacer uso de la API. 

Cuando podamos Adri y yo, nos pondremos con esto.

**Comment by alisanhos** [comment]
Anoche estuvimos Adri y yo intentando arreglar el tema del select pero no lo conseguimos. Hemos decidido dejarlo como estaba, con un Input. 
He arreglado el tema de las ñ y espacios. Ya se puede poner Castilla la mancha o Logroño. Ademas he incluido que se puedan meter tildes y dieresis dado que no se podía anteriormente.
