### ISSUE TITLE
Fix 4 - Trabajos

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#356]
**Descripción general**
Los usuarios piloto han encontrado los siguientes errores en los trabajos:

- Aparecen los botones de editar trabajo si no eres el usuario propietario del servicio.
- En creación de un trabajo si se pone un precio muy alto o un nombre muy grande o en el nombre pones todo números salta un "error fetching the resource".
- Si el precio tiene decimales salta un error (revisar si es comportamiento esperado).
- Se propone añadir un máximo al precio de los trabajos.
- Cuando editas un trabajo desaparece del listado principal.
- Se propone especificar que la experiencia es en años.

**INDICAR EN LA PR SI NO SE HA LLEGADO A IMPLEMENTAR CUALQUIERA DE LAS PROPUESTAS ANTERIORES**

**Comment by alisanhos** [comment]
@adrgarcha o @pabmatang. En mi tarea Fix 3 he tocado el frontend de trabajo para hacerlo responsive y reorganizar un poco la pestaña de detalles de servicios, no comenceis esta tarea hasta que mergee mi tarea a develop.
