### ISSUE TITLE
Fix 8 - Responsive Contratos

### ISSUE THREAD

**Issue by adrgarcha** [ciaolavoro/ciao-lavoro#360]
**Descripción general**
Se busca hacer responsive todas las páginas que incluyan información sobre los contratos como crear contrato, mis contratos...

**Comment by javgrogom** [comment]
La página de mis contratos es responsive:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/764350ac-d756-4565-9c23-13a2eeaaf049)


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/49e863cc-cd8c-4d3a-9e53-63cde4f1f0bc)




Creación de Contrato es el que falla en ser responsive:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/57db463f-c250-4c07-a8c8-ea864154fe18)

Se procede a trabajar con creación de contrato

**Comment by javgrogom** [comment]
Arreglado:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/beb388b2-09e3-46e4-8cd4-d3cde28fca97)


Se procede a realizar el commit
