### ISSUE TITLE
Fix 16 - Rediseñar página de inicio

### ISSUE THREAD

**Issue by Joaquin-Arregui** [ciaolavoro/ciao-lavoro#402]
**Descripción general**
Modificar la pantalla principal para que el banner solo aparezca cuando el usuario no está logueado.

![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72920772/c90a0b2b-9092-42f5-9635-7b34acbc3cfd)

**Comment by javgrogom** [comment]
Todo funciona correctamente. Tras hablarlo con alex se puede dar por finalizada esta tarea
