### ISSUE TITLE
Fix 17 - Arreglar puntos del pago de contrato:

### ISSUE THREAD

**Issue by Joaquin-Arregui** [ciaolavoro/ciao-lavoro#403]
**Descripción general**
Añadir al botón de pago de un contrato un desplegable como el siguiente

![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72920772/8241bd88-2690-469e-85c2-eb868dd814e7)

**Comment by javgrogom** [comment]
Lo he comenzado a hacer
Avisaré si surge algún problema

**Comment by javgrogom** [comment]
Terminado y pendiente de revisión. No ha habido ningún problema
