### ISSUE TITLE
Fix 19 - Arreglar Listado de promocionados

### ISSUE THREAD

**Issue by Joaquin-Arregui** [ciaolavoro/ciao-lavoro#405]
**Descripción general**
El listado de servicios promocionados muestra todos los servicios con valor en el campo de promocionado, y ahora solo debería mostrar solo los servicios en los cuales el campo promocionado, el cual tiene el valor de una fecha es una fecha a menos de un mes de la fecha actual.
También se deberían hacer más notorios los servicios promocionados, la manera actual no se ve correctamente.
![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72920772/94d9f2ca-9d1d-45bd-aafb-35f09c76f659)

**Comment by adrgarcha** [comment]
Se ha arreglado el listado de servicios promocionados en #402.
