### ISSUE TITLE
Fix 24 - Error al pagar un contrato

### ISSUE THREAD

**Issue by javgrogom** [ciaolavoro/ciao-lavoro#417]
Al hacer click en el botón de pagar contrato, en lugar de llevar a la pasarela de pago, se paga solo

https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/a8d4e608-5476-4aeb-8cf0-4e2b078b5707

**Comment by adrgarcha** [comment]
Se ha arreglado en #406.
