### ISSUE TITLE
Fix 25 - pagar usando puntos promocion servicio

### ISSUE THREAD

**Issue by javgrogom** [ciaolavoro/ciao-lavoro#418]
La aplicación devuelve un 400 al intentar pagar usando puntos en la promoción de servicio. Creo que puede ser cosa de backend por la salida de la consola, pero no lo sé con seguridad.
![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/0a0ff276-31b4-46ff-8da2-c961930f7aea)
![image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/da0bd2bb-a61c-469e-bcdd-87cde174885b)

**Comment by alvhidrod** [comment]
Los puntos se consumen, y la fecha de promocion se actualiza aunque no se termine de hacer el pago
La lista de servicios promocionados tanto en la pantalla de inicio como en los propios actúa de forma extraña ya que muestra promocionados todos los servicios que (aparentemente) tengan una fecha en la base de datos

**Comment by alvhidrod** [comment]
Ademas si se usan mas puntos de los que cuesta el pago peta completamente y no deja(los puntos tambien se consumen en este caso)

**Comment by alisanhos** [comment]
> Los puntos se consumen, y la fecha de promocion se actualiza aunque no se termine de hacer el pago La lista de servicios promocionados tanto en la pantalla de inicio como en los propios actúa de forma extraña ya que muestra promocionados todos los servicios que (aparentemente) tengan una fecha en la base de datos

Respecto a esto, ya había otras issues creadas para solucionarlo. El tema del pago está solucionandolo Adrian con la issue #406 .
Sobre la lista de servicios ya esta solucionado con la issue #402

**Comment by alisanhos** [comment]
Ya he encontrado el fallo, es porque stripe no te deja hacer pagos menores de 50 céntimos.

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/ff9cc83e-100f-4eab-867e-ccc04967612e)

**Comment by javgrogom** [comment]
Revisado, todo funciona correctamente. Procedo a borrar issue
