### ISSUE TITLE
Fix 27 - Términos y Condiciones

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#437]
- Revisar nuevamente si existen claúsulas abusivas.
- En los términos indica que la edad mínima es 13 años, mientras que en la aplicación son 16 años. Cambiarlo en los términos.
- Mejorar visualmente el documento de términos.

**Comment by javgrogom** [comment]
https://github.com/ciaolavoro/landingpage/commit/b5ba25b4107c2653e2b13d028cbc6fe14b062b3c

realizada
