### ISSUE TITLE
Fix 28 - Usuario

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#438]
**INICIO DE SESIÓN**

- [x] - Cambiar las credenciales del administrador.

**REGISTRO DE USUARIO**

- [x] - Comprobar que el correo se verifique y exista.
- [x] - Revisar si existen errores de validación que no se están teniendo en cuenta.
- [x] - Quitar los alert para los errores de validación y hacerlo como se realiza en editar perfil por ejemplo.

**EDICIÓN DE USUARIO**

- [x] - Comprobar que el correo se verifique y exista.
- [x] - Revisar la posibilidad de editar el perfil sin cerrar sesión.
- [x] - Revisar si existen errores de validación que no se están teniendo en cuenta.
- [x] - Quitar los alert para los errores de validación y hacerlo como se realiza en editar perfil por ejemplo.
- [x] - Revisar por qué aparece el error de la fecha de nacimiento con la fecha 10/04/2002.

**Comment by javgrogom** [comment]
Cambiada las credenciales del superusuario, ahora es CiaoLavoroAdministratorTeam y usa una contraseña más segura

**Comment by javgrogom** [comment]
Registro de usuario:
 Comprobar que el correo se verifique y exista.

La página lo comprueba y funciona correctamente. Pero hay un problema, si el correo no existe manda un error 400 sin mensaje personalizado:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/c257e3f6-3532-4a69-8d57-16fc47b25147)

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/6d292152-a091-4c55-a8c1-5359f23acc4f)

**Comment by javgrogom** [comment]
Procedo a comprobaar los de edicion de usuario

**Comment by javgrogom** [comment]
- Revisar por qué aparece el error de la fecha de nacimiento con la fecha 10/04/2002.

Comprobado, hay un fallo en el json o algo asi, y no esta relacionado con ninguna fecha concreta.



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/3df1ea3d-b84d-4d11-9459-d10321228396)

**Comment by javgrogom** [comment]
- Revisar por qué aparece el error de la fecha de nacimiento con la fecha 10/04/2002.

Comprobado esto no falla en la edicion de usuario

**Comment by javgrogom** [comment]
Arreglado el problema donde cualquier modificacion en el perfil de usuario llevaba a un error 404.
Se habia eliminado la funcion UserList de backend. Por favor no eliminarla, esa funcion es esencial para el correcto funcionamiento de la edicion de usuario.

**Comment by javgrogom** [comment]
Se ha pasado de esto:
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/7e0e81aa-7dfe-4268-8edf-6be5a06fd620)


A esto:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/6f3afc19-f1a9-4d23-8d80-880ed5fab2f4)

Y de eso a esto:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/31c470b6-0dfb-4f16-bbfe-fba80d52bf63)

**Comment by javgrogom** [comment]
Se ha revisado la validación y ahora valida más restricciones al editar usuario:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/0238d50a-915e-48b6-b12e-aa3e79914a21)

**Comment by javgrogom** [comment]
Tras revisar considero que estos dos requisitos de crear usuario estaban ya implementados


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/3b39107c-e8bd-458d-b5cc-f497e124b760)

Los mensajes salen de forma correcta y valida

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/2c5edf1d-b97d-49e6-831c-29461a3aa944)



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/5faa6762-ba19-4411-a5f3-b513372ac36a)


Y el unico cambio a implementar va a ser cambiar el limite de la fecha pasada a una mas normal, a 100 años

Y ahora está asi:


![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/097095da-22da-427a-928d-70da03cff33f)

**Comment by javgrogom** [comment]
Por lo que he podido comprobar, si pongo correos inventados como loquesea @ fjfkgfkoehgnvjgi . com, la aplicación no deja crear una cuenta, por lo que supongo que si verifica correos.
