### ISSUE TITLE
Fix 29 - Servicio

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#439]
**SERVICIO**

- [x] Poner una tilde en profesión en la búsqueda de servicios.
- [x] Mejorar mensaje de error de la experiencia al crear/editar un servicio. Indicar cuanto es el mínimo de años de experiencia en relación a tu edad.
- [x] Revisar si al crear un servicio, da un error de que ya existe el servicio.
- [x] Añadir un [tooltip](https://ui.shadcn.com/docs/components/tooltip) en el icono del megáfono indicando que se trata de un servicio promocionado.
- [x] Si se pone la experiencia en decimales al crear/editar un servicio da un error.
- [x] Cuando creas más de un servicio, aparece un error indicando que no se puede crear un servicio con la misma profesión, aunque no sea la misma profesión.
- [x] Cuando no se encuentran servicios con los filtros aplicados, que muestre un mensaje de que no se encuentra ningún servicio. Similar a como se hace en contratos.
- [x] Las estrellas de las reseñas se salen de la pantalla en móvil.
- [ ] Al introducir un texto muy largo al crear/editar un servicio, se llega a salir de la pantalla en los detalles.

**PROMOCIONAR**

- [x] Al promocionar un servicio, da un error al poner 0 puntos o puntos decimales. También deja poner -0 puntos y valores no numéricos.
- [x] Si no tienes puntos, que no aparezca el modal para indicar cuantos puntos usar para el descuento.
- [x] Revisar que la pasarela de pago de promoción funcione correctamente.

**Comment by pabcueper** [comment]
Poner una tilde en profesión en la búsqueda de servicios. 👍 
Mejorar mensaje de error de la experiencia al crear/editar un servicio. Indicar cuanto es el mínimo de años de experiencia en relación a tu edad.👍 
Revisar si al crear un servicio, da un error de que ya existe el servicio. ❓  
Añadir un [tooltip](https://ui.shadcn.com/docs/components/tooltip) en el icono del megáfono indicando que se trata de un servicio promocionado.👍 
Si se pone la experiencia en decimales al crear/editar un servicio da un error. 👍 
Cuando creas más de un servicio, aparece un error indicando que no se puede crear un servicio con la misma profesión, aunque no sea la misma profesión. ❓ 
Cuando no se encuentran servicios con los filtros aplicados, que muestre un mensaje de que no se encuentra ningún servicio. Similar a como se hace en contratos.
Las estrellas de las reseñas se salen de la pantalla en móvil.
Al introducir un texto muy largo al crear/editar un servicio, se llega a salir de la pantalla en los detalles.
PROMOCIONAR

Al promocionar un servicio, da un error al poner 0 puntos o puntos decimales. También deja poner -0 puntos y valores no numéricos.
Si no tienes puntos, que no aparezca el modal para indicar cuantos puntos usar para el descuento.
Revisar que la pasarela de pago de promoción funcione correctamente.
