### ISSUE TITLE
Fix 30 - Trabajo

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#440]
- Poner un mínimo de caracteres en el nombre.
- Al crear/editar un trabajo, se puede introducir un precio de 0.0 al introducir 0.00000001.
- Revisar si deja poner decimales al crear/editar un trabajo.

**Comment by Joaquin-Arregui** [comment]
- Se ha limitado el nombre de un trabajo a un mínimo de 5 caracteres sin contar espacios.
 - El precio estimado de un trabajo se ha limitado a un total de 2 decimales, por tanto debería limitarse también en el frontend
 - El backend acepta decimales e integers sin problema.

**Comment by alisanhos** [comment]
En frontend: 
- Limitacion minima en el nombre: 

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/c2d4bc3e-bd2f-4e86-9745-07215075e533)


- Limitacion de decimales en el precio, ademas de no poder poner 0: 

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/561cbaa8-1538-455d-bd2a-2ba41eb9eeb5)

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/fffc6616-2c2d-4dc0-977d-e3474d4b3f97)

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/403ef677-4e36-42db-8ba0-afcc8491e3ce)




![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/3b1a34a5-6dc1-43db-a136-459876205910)
