### ISSUE TITLE
Fix 31 - Contrato

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#441]
- [x] No deja poner decimales en la creación de contrato.
- [x] Revisar si la búsqueda de contratos funciona correctamente.
- [x] Es posible crear un contrato que inicie dentro de 1000 años y dura 10 años. Realizar validaciones más estrictas.
- [x] Revisar si es posible crear un contrato con fecha anterior a la actual.
- [x] Si no tienes puntos, que no aparezca el modal para indicar cuantos puntos usar para el descuento.
- [x] Revisar si existe algún error al indicar un contrato como terminado.
- [x] Al pagar un contrato, da un error al poner 0 puntos o puntos decimales. También deja poner -0 puntos y valores no numéricos.
- [x] Revisar si es posible cancelar un contrato.
- [x] Si tengo más de un contrato con un trabajador, al pagar uno de los contratos se paga automáticamente el otro. Revisar si está relacionado con los estados de los contratos.

**Comment by Samalbalat** [comment]
Sobre este punto: No deja poner decimales en la creación de contrato.
Se ha testeado con 10 , 10,0 y 10.0 y todos los valores funcionan

**Comment by Samalbalat** [comment]
Sobre este punto: Revisar si es posible crear un contrato con fecha anterior a la actual.
Revisen quien ha realizado las restricciones de frontend porque para ellos coge una hora que no es la hora del PC de uso hasta donde me he percatado, mucho ojo con eso por lo demás, no, no se puede hacer

**Comment by Samalbalat** [comment]
Sobre este punto: Revisar si la búsqueda de contratos funciona correctamente.
Los rangos de fechas no funcionaban y tenían ángulo de error porque en front si no se especificaba siempre se pasaba la fecha como '', ahora se comprueba dicho asunto y encima se ha realizado mejorado el listado en este commit 0f636be5c000b282e87db08ca4ed1ae7c4c4f3ab

**Comment by Samalbalat** [comment]
Sobre este punto: Es posible crear un contrato que inicie dentro de 1000 años y dura 10 años. Realizar validaciones más estrictas.
Se ha establecido un máximo de 8 horas por contrato y una dilatación máxima respecto al inicio de 6 meses

**Comment by Samalbalat** [comment]
Sobre este punto: Al pagar un contrato, da un error al poner 0 puntos o puntos decimales. También deja poner -0 puntos y valores no numéricos.
El campo en front debería de ser un campo númerico como en la creación de contrato, este tampoco acepta valores negativos pero si debería de aceptar 0 y enviar un JSON como en la creación de contrato, en esta segunda función incluso acepta las comas para poder pasarlo en backend a float y de float a integer o alternativamente impedir los valores decimales en front

Sin importar eso se ha alterado en backend la línea que lo gestiona para que incluso con decimales se reciba un valor entero
Commit aquí https://github.com/ciaolavoro/ciao-lavoro/commit/f0a78155bc3eae4d02890268a7697c1f045e749d

**Comment by Samalbalat** [comment]
Sobre este punto: Revisar si existe algún error al indicar un contrato como terminado.
No aparentemente pido segunda opinión a @alvhidrod

**Comment by Samalbalat** [comment]
Sobre este punto: Revisar si es posible cancelar un contrato.
No aparentemente pido segunda opinión a @alvhidrod

**Comment by Samalbalat** [comment]
Sobre este punto: Si tengo más de un contrato con un trabajador, al pagar uno de los contratos se paga automáticamente el otro. Revisar si está relacionado con los estados de los contratos.

No sé como están echas las llamadas al backend en front end pero aprecer ser que se ejecutan 2 PUTs por cada contrato al procesar el pago, habría que revisar dicha parte

**Comment by alisanhos** [comment]
Desde frontend en Crear Contrato ya están solucionadas varias cosas:

-  No deja poner decimales en la creación de contrato: ahora si se puede, se debe poner decimales con .
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/d80d7944-cfc2-4de6-b943-7afea4918231)

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/91de9866-5337-4206-a56b-473636b1dfda)

-  Es posible crear un contrato que inicie dentro de 1000 años y dura 10 años. Realizar validaciones más estrictas.
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/8d1e17b8-3df5-4950-969d-a8a035c164c6)

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/38349405-132e-4d9f-8b0f-69aa3c9e366e)

- Revisar si es posible crear un contrato con fecha anterior a la actual: no, no se puede crear. 
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/57d4e938-9ae1-45ea-a128-c2d0ff844871)

**Comment by alisanhos** [comment]
He conseguido arreglar todo lo respecto a Contrato, lo único que no consigo solucionar es el tema del pago:



![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/6b9c86d5-cdd2-43b4-a0a6-5272ab406ba0)

**Comment by alisanhos** [comment]
Disculpad por el último commit, eran cambios correspondientes a otra rama. Por algún motivo no hice bien el cambio de rama por comandos.

**Comment by alvhidrod** [comment]
Revisadas las dos funcionalidades pedidas por @Samalbalat, funcionan como se debe
