### ISSUE TITLE
DOC - Aportar a la base de conocimiento 23/04

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#472]
Pasar el feedback dado en clase a la base de conocimiento común

**Comment by javgrogom** [comment]
https://github.com/ciaolavoro/ciao-lavoro/wiki/Feedback-semana-10-%E2%80%90-23-de-Abril-de-2024

Realizado el contenido de la wiki. Falta aplicar el conocimiento a aportar en la base de conocimiento

**Comment by javgrogom** [comment]
https://github.com/ISPP-2324/BGC/commit/5d7961558fca9ef105a9f53956a77370bc9fd241

Feedback individual disponible en la base de conocimiento. Se procede a aportar para el feedback grupal

**Comment by javgrogom** [comment]
https://github.com/ISPP-2324/BGC/commit/40943f69a7815f8833d90fffa1508a9571a1a354

Feedback grupal disponible en la base de conocimiento.

**Comment by javgrogom** [comment]
https://github.com/ISPP-2324/BGC/pull/111

Se ha mergeado ya en la rama main. Se procede a cerrar la issue.
