### ISSUE TITLE
Fix 4 - Usuarios

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#508]
**Descripción general**

- [x] No permitir que los campos nombre y apellidos tengan espacios en blanco al principio.

- [x] No permitir que los campos nombre y apellidos tengan solo números.

- [x] Permitir solo 1 correo por usuario.

- [x] El placeholder del idioma se sale del marco del input

**Comment by javgrogom** [comment]
Pasamos de esto:

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/29b62c86-a8ab-473b-8f31-113091023fd4)

A esto

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/d32adf07-07f2-40a1-8584-452e111b8dd3)

:

**Comment by javgrogom** [comment]
Arreglado todo
