### ISSUE TITLE
Task 15 - Vista creación Contrato

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#51]
El usuario podrá acceder con un botón o una url a un formulario de creación de contratación.

Esta pantalla debe consistir en una pantalla sencilla con los campos del formulario.

Debe respetar los colores de la aplicación y los márgenes necesarios.

Desde la página se deberá poder acceder a la página principal.

**Comment by pabcueper** [comment]
El usuario podrá acceder con un botón o una url a un formulario de creación de contratación.

Esta pantalla debe consistir en una pantalla sencilla con los campos del formulario.

Debe respetar los colores de la aplicación y los márgenes necesarios.

Desde la página se deberá poder acceder a la página principal.
