### ISSUE TITLE
Fix 7 - Contratos

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#511]
**Descripción general**

- [x] El campo descripción se puede reducir hasta que es ilegible

- [x] Especificar el error que se muestra cuando creamos un contrato de coste 0.

- [x] Se pueden introducir -0 puntos.

- [x] Los clientes son los únicos que pueden finalizar el contrato. Eliminar el botón para los trabajadores.

**Comment by javgrogom** [comment]
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/fbbde6e9-4ee7-4c39-a654-8e5c3b7a801e)
