### ISSUE TITLE
Fix 8 - Reviews

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#512]
**Descripción general**

- [ ] El campo para dejar la review se puede reducir hasta ser ilegible.

- [x] Se pueden hacer reviews de servicios que no he contratado. Además no se permite hacer reviews de servicios contratados.

- [ ] Cuando realizas un comentario te redirige al inicio.

**Comment by alisanhos** [comment]
Respecto al segundo punto, eso se esta arreglando en la fix 3!!!! #503

**Comment by javgrogom** [comment]
Cerrada
