### ISSUE TITLE
Fix 9 - Interfaz

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#513]
**Descripción general**

- [x] Las imágenes del menú principal sobresalen, provocando que no sea responsive.

- [x] Los puntos de un usuario desde el móvil no aparecen.

**Comment by javgrogom** [comment]
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/64b21525-de4f-499a-9427-49de5b28201f)

Logré que aparecieran. Queda hacer que esté bonito.

**Comment by javgrogom** [comment]
![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/72520174/ab4a5323-21a9-42d4-aa50-0c2b118bcd1d)

Arreglado
