### ISSUE TITLE
Fix 10 - Términos y servicios.

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#514]
**Descripción general**

- [x] Especificar que método de identificación vamos a usar (Correo)

- [ ] Los usuarios pueden tener más de una cuenta activa en la aplicación

**Comment by javgrogom** [comment]
https://ciaolavoro.github.io/landingpage/terminosyCondciones.html

**Comment by javgrogom** [comment]
@diegonqui o @alisanhos revisad cuando podais que el TyC esta bien
