### ISSUE TITLE
Task 16 - Vista listado Contrato

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#52]
El usuario podrá acceder con un botón o una url a sus contrataciones.

Esta pantalla debe consistir en un listado sencillo de elementos contratación.

Deberá permitir espacio de ampliación a futuro para poder incluir búsquedas dentro de las contrataciones.

Debe respetar los colores de la aplicación y los márgenes a ambos lados.

Desde la página se deberá poder acceder a la página principal

**Comment by pabcueper** [comment]
El usuario podrá acceder con un botón o una url a sus contrataciones.

Esta pantalla debe consistir en un listado sencillo de elementos contratación.

Deberá permitir espacio de ampliación a futuro para poder incluir búsquedas dentro de las contrataciones.

Debe respetar los colores de la aplicación y los márgenes a ambos lados.

Desde la página se deberá poder acceder a la página principal
