### ISSUE TITLE
Task 19 - Pasar UML a limpio

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#55]
Siguiendo lo hablado en la reunión:

![Image](https://github.com/ciaolavoro/ciao-lavoro/assets/59439742/e13997b1-7bb0-49c3-a5d4-5c9e59cc327d)

**Comment by javgrogom** [comment]
Tras revisar el UML definitivo diría que está bien hecho.

**Comment by Samalbalat** [comment]
Confirmado por parte de los trabajadores de la Issue ratificamos la revisión
