### ISSUE TITLE
Contribución KB

### ISSUE THREAD

**Issue by diegonqui** [ciaolavoro/ciao-lavoro#556]
Tarea dedicada a realizar la contribución a la base de conocimiento común y actualización de la nuestra. @javgrogom es el encargado de realizarlo y @alisanhos encargado de revisarlo.

**Comment by javgrogom** [comment]
https://github.com/ciaolavoro/ciao-lavoro/wiki/Feedback-semana-12-%E2%80%90-7-de-Mayo-de-2024

Nuestra base de conocimientos con el feedback filtrado. Queda por actualizar la base de conocimientos de todos los grupos

**Comment by javgrogom** [comment]
https://github.com/ISPP-2324/BGC/pull/131

Contribución al docusaurio individual y grupal.
Queda redactar el documento report.md
