### ISSUE TITLE
Pensar en un nuevo Killer Opener

### ISSUE THREAD

**Issue by Antonio23337** [ciaolavoro/ciao-lavoro#560]
Tarea dedicada a pensar el Killer Opener definitivo que ensayaremos el Lunes 20/05 y realizaremos el Martes 21/05. @Antonio23337 y @alvhidrod serán los encargados de pensar y recopilar las ideas de TODO el grupo y llegar a un consenso.

**Comment by javgrogom** [comment]
De killer opening de me ha ocurrido la siguiente idea:
-entra un compañero disfrazado de limpiador y empieza a limpiar el escenario, entonces aparece uno vestido elegante (como si fuera el jefe) y le suelta un "estas despedido".
Entonces el barrendero se pregunta algo tipo "y que hago ahora?".
Entonces entra samu y le dice "oye amigo, y si pruebas a trabajar para particulares? Podrias usar ciaolavoro". Entonces el barrendero le pregunta que es ciaolavoro y ya ahi samu conecta el killer opening con la presentación
