### ISSUE TITLE
Task 26 - (DOC) Presentación

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#87]
Debe llamarse X-presentacion.pdf

Debe seguir el siguiente orden ESTRICTAMENTE y tener en cuenta el FEEDBACK:

1. 15% - Killer opener, elevator pitch, resumen analisis de competidores, resumen TCO (distinguir entre capex y opex), cuanto llevamos gastado de presupuesto, resumen ROI (pesimistas,realistas y optimistas a corto y medio plazo). Estado del commitment agreement, cambio de roles. QUITAR DAFO. Uso de IA por encima.

2. 15% - Demo del prototipo del sprint 1. 

3. 40% - Retrospectiva: analisis de rendimiento del equipo (formulas y numero de cada miembro, con gráficas de resultado). Analisis de calidad con Codacy, gestión de riesgos, problemas encontrados, solución propuesta, lecciones aprendidas. 

4. 10% - Clokify, reloj, cuanto hemos invertido, graficas mas completas. 

5. 10% - Gestión de usuarios pilotos: feedback, planificación para el siguiente sprint (con el calendario quedó guapo). 

6. 10% - Planificación del Sprint 2 ESPECIFICO. Con lo que nos quedaria para el Sprint 3.

7.  QR para la landing page y un email de contacto para el feedback.

**Comment by JoseLuisCobo17** [comment]
DONE
