### ISSUE TITLE
Task 28 - (DOC) Individual Performance Evaluation

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#89]
Debe llamarse X-PerformanceEvaluation.pdf.

Rellenar entre todos el documento que ya esta creado de la entrega anterior, para completar lo hecho en esta entrega.

**Comment by javgrogom** [comment]
@Joaquin-Arregui tambien estas asignado a esta tarea, lo que pasa es que el tope de github es 10 personas.
