### ISSUE TITLE
Task 33 - (DOC) Sprint Planning

### ISSUE THREAD

**Issue by alisanhos** [ciaolavoro/ciao-lavoro#94]
Debe llamarse X-SprintPlanning.pdf.

Un documento en el que pongamos toda la planificacion de los sprint. 

Detallando las tareas del S1 y S2, indicando las cosas que no han dado tiempo en el S1 y pasan a hacerse en el S2.

**Comment by javgrogom** [comment]
Lo he revisado, y exceptuando un par de errores ortograficos que he corregido, parece que está perfecto.
